### PR TITLE
provide convenience function for the AVF method

### PR DESCRIPTION
**Pull request by ranocha**
I think it would be nice to have a convenience function returning the B-series of the AVF method. However, I'm not sure about the best interface. We could have

1. `bseries(AverageVectorFieldMethod(), up_to_order)`
2. `average_vector_field_method(up_to_order)`

with options to allow different types of the coefficients, e.g.,

1. `bseries(AverageVectorFieldMethod(Float64), up_to_order)`
2. `average_vector_field_method(Float64, up_to_order)`

Option 1 would be more close to most methods of `bseries` we have so far - but the return value of `AverageVectorFieldMethod()` would have no further use (at the moment). Option 2 is more close to something like `zeros`.

What would you prefer, @ketch?

### CODE REVIEW

**Comment by ketch** [comment]
I have asked @Sondar74 to develop some capabilities for CSRK methods (of which AVF2 is an example).  These methods can be fully represented by a combination of:

- A polynomial basis
- A (real-valued) matrix

So it might make sense to implement your 1st approach, where `AverageVectorFieldMethod()` returns the matrix (and possibly a field indicating which polynomial basis it relates to).  The next step is to write a function that computes the elementary weights from this representation, and @Sondar74 is working on that now.

**Comment by ranocha** [comment]
Great! I will implement the first approach here so that we have the convenience method `bseries(AverageVectorFieldMethod(), up_to_order)` soon.

**Comment by ranocha** [comment]
I've updated this PR. It would be nice if you could have a look, @ketch

**Comment by ketch** [comment]
This looks fine.  Once @Sondar74 has written the more general version, we may consider replacing this one that is a particular case (or perhaps we will keep it, since the 2nd-order AVF method is particularly interesting).

**Pull request merged**
